theme: jekyll-theme-cayman

title: Scalable Mind-Wandering Detection for MOOCs: A Webcam-Based Approach
description: This is a project for learners' Mind-Wandering Detection during watching lecture videos based on Eye Tracking with Tobii or WebGazer.js.